### ISSUE TITLE
Adjustable percentage in HUD steps

### ISSUE THREAD

**Issue by etrahretep** [henrikruscon/alcove-releases#14]
### Problem

Percentage in HUD steps not adjustable

### Expected behavior

Would like adjustable steps in percentage for both display and sound HUD.  Now standard is 6%.

**Comment by henrikruscon** [comment]
Not possibly, Alcove doesn't actually adjust anything, it just visually shows what is being changed. For Alcove to adjust changes it would require full keyboard access, which is not a permission I want to require at this time.

I might revisit this in the future though. Closing for now.
