### ISSUE TITLE
Function suggestion for "Expand notch on hover"

### ISSUE THREAD

**Issue by meguoe** [henrikruscon/alcove-releases#2]
When the "Expand notch on hover" feature is enabled, can a setting for hover duration be added, such as triggering the expansion only after hovering for 2 seconds?

![image](https://github.com/user-attachments/assets/49ea4814-abe0-441e-8abf-2f10ffdc1daf)

**Comment by henrikruscon** [comment]
Sure, I will add this as well. Thank you for the suggestion!

**Comment by henrikruscon** [comment]
This is now released in v1.1.0
