### ISSUE TITLE
Improve offline support

### ISSUE THREAD

**Issue by Coops0** [henrikruscon/alcove-releases#3]
Hi-

I bring my laptop to and from school everyday, and my school's network blocks unapproved domains, so Alfred's API servers are blocked. Throughout the day, Alfred will seemingly crash, and will not even respond to relauches if I am not connected to a VPN. Sometimes also if I leave my Mac off for a few hours at home, I will find it has crashed.

**Comment by henrikruscon** [comment]
Unfortunately, Alcove currently requires an internet connection to function. I will look into improving offline support in a future update, thank you for taking your time reporting this issue.

**Comment by henrikruscon** [comment]
This one is fixed in the upcoming v1.1.0 release, Alcove will now allow you to remain offline for a week without an internet connection.

**Comment by henrikruscon** [comment]
This is now released in v1.1
