### ISSUE TITLE
App stops working after opening Guitar Pro 8

### ISSUE THREAD

**Issue by brunoguardieiro** [henrikruscon/alcove-releases#5]
After opening Guitar Pro 8 Alcove stops showing VOLUME UP or DOWN. I have to restart the app so it starts showing volume changes again. 

I know Guitar Pro 8 messes with audio input / output when opened so maybe it is related to that ?

Anyway, hope it helps.

Many thanks in advance.

**Comment by henrikruscon** [comment]
Definitely sounds related to that, Alcove simply checks the volume for your main output device, if it fails to do such, it wouldn't show the HUD anymore. Not quite sure what the solution is here, maybe the issue is actually with Guitar Pro 8?

Thank you for taking your time.

**Comment by brunoguardieiro** [comment]
Actually, today I experienced the same issue but without using Guitar Pro 8 app. Actually, I was simply changing volume, without using any bluetooth or external device. Please, I'd gladly share more info about the issue, but I need guidance here. Many thanks !

**Comment by henrikruscon** [comment]
Can you try the new v1.1 release and see if this issue remains?

**Comment by brunoguardieiro** [comment]
I've also posted updates on this issue on your github page.
Can't wait to try the new version ! Congrats on the great job !

---

Bruno Guardieiro
***@***.***
***@***.***
+55 11 98279-7899
Em 31 de dez. de 2024, 00:34 -0300, Henrik ***@***.***> escreveu:

**Comment by 0x5b62656e5d** [comment]
@brunoguardieiro Does this still happen with [latest release](https://github.com/henrikruscon/alcove-releases/releases/latest)?

**Comment by brunoguardieiro** [comment]
Working flawlessly so far.
Tested while changing sound outputs, using Guitar Pro, and so far running perfect.
Congrats !

**Comment by henrikruscon** [comment]
Splendid, solved then.
