### ISSUE TITLE
Another devices connection visible 

### ISSUE THREAD

**Issue by lickerish** [henrikruscon/alcove-releases#6]
When connecting with i.e. latest Bose/Sony headphones and Earbuds it would be great to see them pop up exactly the same like with Airpods. Not sure if that is possible but I assume those devices exchange similar information as AirPods to help you identify what was connected.

Example devices to start with:
- Bose QuietComfort Ultra Earbuds
- Bose QuietComfort Ultra HeadPhones
- Sony WF-1000XM5
- Sony WH-1000XM5
- ...

**Comment by henrikruscon** [comment]
Unfortunately this is not gonna be possible, the data will be entirely different (batteries and such) and also I don't have the 3D models matching for any of those headphones.

AFAIK Apple doesn't support this either on iOS? As in, they only show the connectivity modal for their own headphones (AirPods + Beats).

**Comment by lickerish** [comment]
I see. Yes, iOS does not support it either but I thought that with custom software it is possible to observe new Bluetooth connections and render "known" devices meaning those preconfigured in an app. Newer devices like those I mentioned expose battery level but I am not sure what despite that i.e if there is any general name or ID that can be correlated with specific model. 

From what I understood there is a event or whatever that you handle that is specific for apple products only and that causes the issue. 

Btw. There is always a possibility to show only 2D image at first or use generic 3D model and 2D image of headphones as default. 
I guess 3D models are doable but I would have to think how to do it smart without modeling each pair from scratch. So if you think it would be doable to add the functionality then I will let you know what we can do with models.

Thanks for looking into it btw!
