### ISSUE TITLE
The application crashes when working with Apple Music 

### ISSUE THREAD

**Issue by kemroy3932** [henrikruscon/alcove-releases#8]
**Bug Detection in Alcove:**

1. **Launching the App and Starting a Track:**
   - Open Apple Music on the MacBook.
   - Select any track and start playback.
   - Verify that the playback animation functions correctly.

2. **Connecting AirPods Pro 2:**
   - Connect the AirPods to the MacBook.
   - Ensure the track continues playing and the animation works.

3. **Automatic Device Switching for AirPods:**
   - Start playing any track on the iPhone.
   - Wait for **AirPods Pro 2 to automatically switch from the MacBook to the iPhone**.

4. **Returning to the MacBook:**
   - Start playing any track on the MacBook.
   - Wait for the AirPods to automatically reconnect to the MacBook.
   - Check if the Alcove animation works.

5. **Device Conflict Issue:**
   - Repeat steps 3 and 4 several times. This will eventually trigger an Apple Music notification about playback restrictions: "Playback is only allowed on one device at a time...." 
   - Even if only the MacBook is actively playing, the track may stop automatically. After multiple attempts to restart the track and receiving the same notification, the app crashes.

**Key Points:**
- The Alcove app crashes more frequently after several cycles of automatic device switching.
- It is unknown whether other music apps cause the same bug.  
- Tested on MacBook Pro 16 M1 2021, macOS Sequoia 15.2.  
- App version: 1.0.3.

**Comment by henrikruscon** [comment]
Should be fixed in v1.1.0 release
